// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(LaptopContext))]
    [Migration("20240808102632_ok")]
    partial class ok
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.Property<int>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_HoaDon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoaDon"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IdKhach")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KhachHangSDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ThanhTien")
                        .HasColumnType("bigint");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(32)
                        .HasColumnType("nchar(32)")
                        .IsFixedLength();

                    b.HasKey("IdHoaDon")
                        .HasName("PK__HoaDon__14AFCFC572CFA4AA");

                    b.HasIndex("KhachHangSDT");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("DAL.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("IdHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_HoaDonChiTiet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoaDonChiTiet"), 1L, 1);

                    b.Property<decimal?>("Gia")
                        .HasColumnType("money");

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("ID_HoaDon");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    b.Property<int>("IdVoucher")
                        .HasColumnType("int")
                        .HasColumnName("ID_Voucher");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SoLuongSanPham")
                        .HasColumnType("int");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdHoaDonChiTiet")
                        .HasName("PK__HoaDonCh__A6583769B0D9A127");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdVoucher");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("DAL.Models.KhachHang", b =>
                {
                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SDT");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("DAL.Models.SanPham", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_SanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanPham"), 1L, 1);

                    b.Property<string>("Cpu")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CPU");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("money");

                    b.Property<string>("Gpu")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("GPU");

                    b.Property<string>("HangSanXuat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Img")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("IMG");

                    b.Property<string>("ManHinh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pin")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Ram")
                        .HasColumnType("int")
                        .HasColumnName("RAM");

                    b.Property<int?>("Rom")
                        .HasColumnType("int")
                        .HasColumnName("ROM");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdSanPham")
                        .HasName("PK__SanPham__617EA39232199A0C");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Voucher", b =>
                {
                    b.Property<int>("IdVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Voucher");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVoucher"), 1L, 1);

                    b.Property<DateTime?>("HieuLucDen")
                        .HasColumnType("datetime");

                    b.Property<string>("MaGiamGia")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("NgayRaMat")
                        .HasColumnType("datetime");

                    b.Property<int?>("PhanTramGiamGia")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(32)
                        .HasColumnType("nchar(32)")
                        .IsFixedLength();

                    b.HasKey("IdVoucher")
                        .HasName("PK__Voucher__7D975E3EAE6101D1");

                    b.HasIndex(new[] { "MaGiamGia" }, "UQ__Voucher__EF9458E598139C77")
                        .IsUnique()
                        .HasFilter("[MaGiamGia] IS NOT NULL");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.HasOne("DAL.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangSDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("DAL.Models.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonChi__ID_Ho__440B1D61");

                    b.HasOne("DAL.Models.SanPham", "IdSanPhamNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonChi__ID_Sa__44FF419A");

                    b.HasOne("DAL.Models.Voucher", "IdVoucherNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdVoucher")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonChi__ID_Vo__45F365D3");

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdSanPhamNavigation");

                    b.Navigation("IdVoucherNavigation");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DAL.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DAL.Models.SanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DAL.Models.Voucher", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
